#!/usr/bin/node

const esbuild = require("esbuild");

esbuild.buildSync({
  entryPoints: ["src/index.ts", "src/legacy.ts"],
  outdir: "dist",
  format: "esm",
  outExtension: { ".js": ".esm.js" },
});

esbuild.buildSync({
  entryPoints: ["src/index.ts", "src/legacy.ts"],
  outdir: "dist",
  format: "cjs",
  outExtension: { ".js": ".cjs.js" },
});
